routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('vehicle','VehiclesController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/vehicle.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class vehicle extends Model
{
    protected $fillable = [

        'id', 'make', 'model', 'license_number','license_expiry'

    ];
    protected $hidden = [



    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/VehiclesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\vehicle;

class VehiclesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vehicles = vehicle::latest()->paginate(5);

        return view('vehicle.index',compact('vehicles'))
            ->with('i', (request()->input('page', 1) - 1) * 5);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('vehicle.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'make' => 'required',
            'model' => 'required',
            'license_number' => 'required',
            'license_expiry' => 'required',

        ]);

        vehicle::create($request->all());

        return redirect()->route('vehicle.index')
            ->with('success','vehicle created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $vehicles = vehicle::find($id);
        return view('vehicle.show',compact('vehicles'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vehicles = vehicle::find($id);
        return view('vehicle.edit',compact('vehicles','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $vehicles = vehicle::find($id);
        $vehicles->make = request('make');
        $vehicles->model = request('model');
        $vehicles->license_number = request('license_number');
        $vehicles->license_expiry = request('license_expiry');



        $vehicles->save();
        $request->validate([

            'make' => 'required',
            'model' => 'required',
            'license_number' => 'required',
            'license_expiry' => 'required',
        ]);
        $vehicles->update($request->all());

        return redirect()->route('vehicle.index')
            ->with('success','vehicle updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $vehicles = vehicle::find($id);

        if(empty($vehicles)) {
            return;
        }

        $vehicles->delete();

        return redirect()->route('vehicle.index')
            ->with('success','vehicle deleted successfully');
    }
}

resources/views/interface/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
   <!-- BEGIN HEAD -->
   <meta charset="utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <title>{{ config('app.name') }}</title>
    <link href="{{asset('interface/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('interface/fonts/glyphicons.css')}}" rel="stylesheet" type="text/css" />


   </head>
   <!-- END HEAD -->



   <body class=" ">




           @yield('content')






       <script src="{{asset('interface/js/bootstrap.min.js')}}"></script>


   </body>



</html>

resources/views/vehicle/create.blade.php
@extends('interface.master')
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">

        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('vehicle.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('vehicle.store') }}" method="POST">
    @csrf
  

    <div class="row">
        <div class="col-lg-12">
            <section class="box has-border-left-3">
                <header class="panel_header gradient-blue">
                    <h2 class="title pull-left w-text">Add new vehicle</h2>
                </header>
                <div class="content-body">
                    <div class="row">
                        <div class="form-container mt-20 no-padding-right no-padding-left over-h">

                            <div class=" col-xs-12">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label class="form-label">Make</label>
                                                <span class="desc">e.g.  "Honda"</span>
                                                <div class="controls">
                                                    <i class=""></i>
                                                    <input type="text" class="form-control"  name="make">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label class="form-label">model</label>
                                                <span class="desc"> e.g.  "civic"</span>
                                                <div class="controls">
                                                    <i class=""></i>
                                                    <input type="text" class="form-control"  name="model">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label class="form-label">license_number</label>
                                                <span class="desc">e.g. "1548156486"</span>
                                                <div class="controls">
                                                    <i class=""></i>
                                                    <input type="text" class="form-control" name="license_number">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label class="form-label">license_expiry</label>
                                                <span class="desc">e.g. "12/1/2021"</span>
                                                <div class="controls">
                                                    <i class=""></i>
                                                    <input type="date" class="form-control"  name="license_expiry">
                                                </div>
                                            </div>
                                        </div>



                                        <div class="pull-right mt-30 mr-10">
                                            <button type="submit" class="btn btn-primary btn-corner right15"><i class="fa fa-check"></i> Add</button>

                                        </div>

                                    </div>
                                </div>

                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
   
</form>
@endsection

resources/views/vehicle/edit.blade.php
@extends('interface.master')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit vehicle</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('vehicle.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('vehicle.update',$vehicles->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Make:</strong>
                    <input type="text" name="make" value="{{ $vehicles->make }}" class="form-control" placeholder="make">
                </div>
            </div>
             <div class="col-xs-12 col-sm-12 col-md-12">
                 <div class="form-group">
                     <strong>Model:</strong>
                     <input type="text" name="model" value="{{ $vehicles->model }}" class="form-control" placeholder="model">
                 </div>
             </div>
             <div class="col-xs-12 col-sm-12 col-md-12">
                 <div class="form-group">
                     <strong>license_number:</strong>
                     <input type="text" name="license_number" value="{{ $vehicles->license_number }}" class="form-control" placeholder="license_number">
                 </div>
             </div>
             <div class="col-xs-12 col-sm-12 col-md-12">
                 <div class="form-group">
                     <strong>license_expiry:</strong>
                     <input type="text" name="license_expiry" value="{{ $vehicles->license_expiry }}" class="form-control" placeholder="license_expiry">
                 </div>
             </div>


            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/vehicle/index.blade.php
@extends('interface.master')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2></h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('vehicle.create') }}"> Create New vehicle</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Make</th>
            <th>Model</th>
            <th>license_number</th>
            <th>license_expiry</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($vehicles as $vehicle)
        <tr>
            <td>{{ $vehicle->id }}</td>
            <td>{{ $vehicle->make }}</td>
            <td>{{ $vehicle->model }}</td>
            <td>{{ $vehicle->license_number }}</td>
            <td>{{ $vehicle->license_expiry }}</td>
            <td>
                <form action="{{ route('vehicle.destroy',$vehicle->id) }}" method="POST">
   
                  <!--  <a class="btn btn-info" href="{{ route('vehicle.show',$vehicle->id) }}">Show</a>-->
    
                    <a class="btn btn-primary" href="{{ route('vehicle.edit',$vehicle->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    {!! $vehicles->links() !!}
      
@endsection

resources/views/vehicle/show.blade.php
@extends('interface.master')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show vehicle</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('vehicle.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">

        <table class="table table-bordered">
            <tr>
                <th>No</th>
                <th>make</th>
                <th>model</th>
                <th>license_number</th>
                <th>license_expiry</th>

            </tr>

                <tr>
                    <td>{{$vehicles->id }}</td>
                    <td>{{ $vehicles->make }}</td>
                    <td>{{ $vehicles->model }}</td>
                    <td>{{ $vehicles->license_number }}</td>
                    <td>{{ $vehicles->license_expiry }}</td>


                </tr>

        </table>
    </div>
@endsection